x-db-env: &db-env
  DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/subtrack}

services:
  db:
    profiles: ["localdb"]
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subtrack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
    networks:
      - subtrack

  migrate:
    depends_on:
      db:
        condition: service_healthy
        required: false
    profiles: ["migrate"]
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    command: "bun run db:migrate:deploy"
    environment:
      <<: *db-env
    networks:
      - subtrack

  seed:
    depends_on:
      migrate:
        condition: service_completed_successfully
        required: false
      db:
        condition: service_healthy
        required: false
    profiles: ["seed"]
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    command: "bun run db:seed"
    environment:
      <<: *db-env
    networks:
      - subtrack

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./apps/api/.env
        required: false
    environment:
      PORT: 8080
      <<: *db-env
    healthcheck:
      test: ["CMD-SHELL", "bun run healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.priority=10"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    networks:
      - subtrack

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./apps/web/.env
        required: false
    environment:
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.priority=1"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    networks:
      - subtrack

  traefik:
    image: traefik:v3
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=subtrack"
      - "--entrypoints.web.address=:80"
      - "--log=true"
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "3000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - subtrack

volumes:
  postgres_data: null
networks:
  subtrack:
    driver: bridge
    name: subtrack
